# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 1000

# -----------------------kinova------------------------------------

joint_1_position_controller:
  joint: kortex_joint_1
  pid:
    d: 2.0
    i: 0.0
    p: 3000
  type: effort_controllers/JointPositionController
joint_2_position_controller:
  joint: kortex_joint_2
  pid:
    d: 0.0
    i: 0.0
    p: 50000.0
  type: effort_controllers/JointPositionController
joint_3_position_controller:
  joint: kortex_joint_3
  pid:
    d: 0.0
    i: 0.0
    p: 3000.0
  type: effort_controllers/JointPositionController
joint_4_position_controller:
  joint: kortex_joint_4
  pid:
    d: 0.0
    i: 0.0
    p: 50000.0
  type: effort_controllers/JointPositionController
joint_5_position_controller:
  joint: kortex_joint_5
  pid:
    d: 0.2
    i: 0.0
    p: 750.0
  type: effort_controllers/JointPositionController
joint_6_position_controller:
  joint: kortex_joint_6
  pid:
    d: 1.0
    i: 0.0
    p: 5000.0
  type: effort_controllers/JointPositionController
joint_7_position_controller:
  joint: kortex_joint_7
  pid:
    d: 0.0
    i: 0.0
    p: 100.0
  type: effort_controllers/JointPositionController